parameters:
  name: ''
  displayName: ''
  matrix: {}
  msBuildArgs: ''
  platform: ''
  solution: ''
  vmImage: ''
jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    msBuildArgs: ${{ parameters.msBuildArgs }}
    platform: ${{ parameters.platform }}
    solution: ${{ parameters.solution }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  steps:
  - checkout: self
    submodules: recursive
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: $(solution)
      platform: $(platform)
      configuration: $(configuration)
      msbuildArgs: /m $(msBuildArgs)
